# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='caption',
            field=models.CharField(max_length=100, verbose_name='caption'),
        ),
    ]
