# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('treemenus', '0002_auto_20180112_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='legend',
            field=models.CharField(blank=True, max_length=200, verbose_name='caption'),
        ),
    ]
