# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenus', '0003_auto_20180112_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_url_target',
            field=models.CharField(blank=True, choices=[('_blank', 'Load in a new window'), ('_self', 'Load in the same frame as it was clicked'), ('_parent', 'Load in the parent frameset'), ('_top', 'Load in the full body of the window')], default='_self', max_length=255, null=True, verbose_name='Menu URL Target'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(max_length=60, verbose_name='icon'),
        ),
    ]
